### PR TITLE
add close

### PR DESCRIPTION
**Pull request by DJHooligan**
this fixes chromedriver not closing

### CODE REVIEW

**Comment by openbullet** [comment]
Hey, I think the `Quit()` method is a stronger way to close the browser, there is no need to call both.
Please read here
https://www.geeksforgeeks.org/how-to-use-close-and-quit-method-in-selenium-python/

```
While doing stuff with selenium multiple browsers with multiple tabs will normally opens in order to close these tabs close() and quit() methods are used. close() method is used to close the current browser window on which the focus is set, on the other hand quit() method essentially calls the driver.dispose method that successively closes all the browser windows and ends the WebDriver session graciously.
```

So I don't think this PR will improve anything. Please feel free to explain if you have a different take on this.

**Comment by DJHooligan** [comment]
Hey, if you try to run a config with selenium, with current rurilib, drivers don't get killed,
if you compile "my" version of rurilib drivers do get killed...
so it does matter
regards
________________________________
Van: openbullet ***@***.***>
Verzonden: donderdag 16 juni 2022 7:52
Aan: openbullet/OpenBullet2 ***@***.***>
CC: DJHooligan ***@***.***>; Author ***@***.***>
Onderwerp: Re: [openbullet/OpenBullet2] add close (PR #743)


Hey, I think the Quit() method is a stronger way to close the browser, there is no need to call both.
Please read here
https://www.geeksforgeeks.org/how-to-use-close-and-quit-method-in-selenium-python/

While doing stuff with selenium multiple browsers with multiple tabs will normally opens in order to close these tabs close() and quit() methods are used. close() method is used to close the current browser window on which the focus is set, on the other hand quit() method essentially calls the driver.dispose method that successively closes all the browser windows and ends the WebDriver session graciously.


So I don't think this PR will improve anything. Please feel free to explain if you have a different take on this.

**Comment by openbullet** [comment]
Oh I didn't know that this was an issue with the chromedriver itself. Thanks for the heads up, I will merge.

**Comment by DJHooligan** [comment]
Chromium will start if you setup a user in [dockerfile](https://github.com/ebidel/lighthouse-ci/blob/master/builder/Dockerfile#L35-L40) .
(https://developer.chrome.com/blog/headless-chrome/)
regards,

**Comment by meinname** [comment]
I am against this change. 
I tried long time ago to run OB2 in Docker as an unprivileged user.
But i noticed a lot of problems with the UserData volume cause Docker is using the UserID and GroupID of it's Container which might be totally different than the one of the mounted Volume.

So either users have to start the Docker Container in a more complicated way or we produce a file permission mess the Users system - depending on the Host configuration. (also think of multiuser systems and mounted folders from a NAS or so - most solutions only have a workaround for user+group ID 0:0 but not some random other)

Some of these Problems can be tackled somehow on a linux host for sure. - But also for Windows and MacOS?

**Pull request merged**
