### PR TITLE
Add LoadOnlyDocumentAndScript option

### PR DESCRIPTION
**Pull request by Meliio**
sorry if this sucks it's the first time I tried and I can't build the solution to see if it really works ^^'

### CODE REVIEW

**Comment by openbullet** [comment]
Hey, thank you for the PR we will review it shortly.

Just a question, won't this only work when using the New Page block? Because with the Open Browser block, a new page is already instanced (with default behaviour) as you can see below

https://github.com/openbullet/OpenBullet2/blob/8090fc85be2417c05f7ef6780c4e3a88d03dc88a/RuriLib/Blocks/Puppeteer/Browser/Methods.cs#L70

so your option will have no effect here. Isn't it better to put this in a separate method and then call it from both the New Page block and the Open Browser block?

**Comment by openbullet** [comment]
Also it would be nice to add at least the English entry in the correct `.resx` file so that it's displayed nicely on the page, otherwise the localization middleware won't find anything with the key you added.

**Comment by openbullet** [comment]
If you want me to merge it as it is and then add those things myself let me know!

**Comment by Meliio** [comment]
oh yes you can ? i try without success when à build ob master my browser don't found all files like css/js ..

**Pull request merged**
