### PR TITLE
Heavily modified RuriLib.HTTP

### PR DESCRIPTION
**Pull request by RydjGit**
-Added Support for System.IO.PipeLInes For Higher performance HTTP Parsing.
-Code Is much easier to maintain
-Chunked Transfer-encoding accurate parsing
-Reads the responce as is no need to look for signature.
-Less garbage collection using Span<T>

More improvements can be made.

### CODE REVIEW

**Comment by openbullet** [comment]
Thank you for the PR. I ported over that code 1:1 from Extreme.NET (xNet) and couldn't manage to rewrite it as it was resembling the following image.

spaghetti

I will review this tonight and merge it!

**Comment by Laiteux** [comment]
Good job!

**Comment by openbullet** [comment]
@RydjGit this PR introduced a bug, where if the server is misconfigured and doesn't send the `Content-Length` header (and it happens in some cases) we are not reading the response.

This is making some users stay on OB1 because of the impossibility to read the response source. The bug was not present prior to this PR.

Is there any chance you could look into it? I can provide a URL if you PM me on the forum or send me a mail.
Otherwise I will be restoring part of the original code and giving users the choice to use one or the other method to read the response through a block parameter, as a (hopefully temporary) fix.

**Comment by openbullet** [comment]
There are no `Content-Length`, `Content-Encoding` and `Transfer-Encoding` headers (only `Content-Type`) so the response falls into this category

https://github.com/openbullet/OpenBullet2/blob/master/RuriLib.Http/HttpResponseBuilder.cs#L317

But either the method returns before being able to read everything or there is something wrong because it doesn't pick up any content but if you put fiddler in between you will actually see there is a content and it will work correctly.

I will open an issue about this so we can track it better.

**Pull request merged**
