### PR TITLE
Socks4-5 authentication in puppeteer

### PR DESCRIPTION
**Pull request by tracsgh**
Support for socks proxy authentication in puppeteer using [TheSuunny/Yove.Proxy](https://github.com/TheSuunny/Yove.Proxy). Inside, it runs a local http proxy and redirects traffic to the socks proxy. A simple but working trick for solving #68 :)

### CODE REVIEW

**Comment by openbullet** [comment]
Thanks for the PR we will review it tomorrow!

**Comment by meinname** [comment]
OK from me

**Comment by amrmostafa800** [comment]
thank you it work now but it very slow
i think https://github.com/apify/proxy-chain will work good than yove.proxy
it make local proxy too

**Comment by openbullet** [comment]
@amrmostafa800 your solution uses node.js while this uses C# so it's easy to integrate this while it's really hard to integrate yours

**Comment by tracsgh** [comment]
I just tested it. This looks like a bug in the config editor. Very strange bug or I don't know what it is. I created a local c# project and made a request through puppeteer and yoveproxy, everything works fast(1-2s). But in the config editor, loading a simple page takes 30 seconds for me. Also the created task with this config worked quickly

Sorry for my English, I don't know it well

**Comment by openbullet** [comment]
> 
> 
> I just tested it. This looks like a bug in the config editor. Very strange bug or I don't know what it is. I created a local c# project and made a request through puppeteer and yoveproxy, everything works fast(1-2s). But in the config editor, loading a simple page takes 30 seconds for me. Also the created task with this config worked quickly
> 
> Sorry for my English, I don't know it well

Please open a new issue and someone will look into it, thank you!

**Comment by amrmostafa800** [comment]
i think if make new program 
import socks5 proxy with authentication than start socks5 server localhost
when request send to localhost proxy send it to random proxy than get result
Sorry my english bad

**Comment by amrmostafa800** [comment]
@tracsgh i open issue Because you didn't open one :D
https://github.com/openbullet/OpenBullet2/issues/119

**Pull request merged**
